package com.kcteam.app.types

/**
 * Created by rp : 30-10-2017:12:40
 */
enum class TopBarConfig {
    HOME, BACK, ADDSHOP, DASHBOARD, SHOPLIST, MAPVIEW, GPS, CART, ADDATTENDANCE, CARTDETAILS, LOGOUTSYNC, REIMBURSEMENT,SHOPLISTV1, VISITREPORTDETAILS,
    NOTIFICATION, SEARCHLOCATION, SEARCHLOCATIONFROMADDSHOP, TARGETPLAN, TARGETPLANBACK, TARGETPLANDETAILSBACK, TARGETPLANGPS,
    ALLSHOPLIST, ACTIVITYMAP, ORDERLIST, LOCALSHOP, MEMBERSHOPLIST, OFFLINESHOPLIST, OFFLINEMEMBERLIST, TIMESHEETLIST, ONLINEMEMBERLIST,
    ACTIVITSHOP, WEATHERMAP, TASKLIST, MEMBERACTIVITYMAP, ATTENDENCELIST, ATTENDENCEBACKLIST, LEAVELIST, CHATBOT, CHATUSER, NEWGROUP,
    CHAT, SHOPDETAILS, CHATBOTSHOP, BEATLIST, MICROLEARNING, CUSTOMER,

    PHOTOREG,NEWORDERSCRCART,NEWORDERCART,LEADFR,TEAMMAP,DISTWISEORDER
}